# Generated by Django 6.1.1 on 2026-09-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('remote', models.BooleanField(default=False)),
                ('stream', models.CharField(choices=[('backend', 'Backend Engineering'), ('fullstack', 'Full Stack'), ('microservices', 'Microservices'), ('cloud', 'Cloud Native'), ('data', 'Data Engineering'), ('devops', 'DevOps / SRE'), ('mobile', 'Mobile Backend'), ('fintech', 'FinTech'), ('enterprise', 'Enterprise Java')], default='backend', max_length=20)),
                ('experience_level', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior (0-2 yrs)'), ('mid', 'Mid-Level (2-5 yrs)'), ('senior', 'Senior (5-8 yrs)'), ('lead', 'Lead / Principal (8+ yrs)')], default='mid', max_length=10)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('skills', models.CharField(help_text='Comma-separated skills', max_length=500)),
                ('posted_at', models.DateField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-posted_at'],
            },
        ),
    ]
