from django.core.management.base import BaseCommand

from jobs.models import Job


JOBS_DATA = [
    {
        'title': 'Senior Java Spring Boot Developer',
        'company': 'Goldman Sachs',
        'location': 'New York, NY',
        'remote': False,
        'stream': 'fintech',
        'experience_level': 'senior',
        'salary_min': 150000,
        'salary_max': 200000,
        'is_featured': True,
        'skills': 'Java, Spring Boot, Hibernate, REST API, SQL, Microservices, Kafka, AWS',
        'description': 'Join our engineering team to build next-generation trading platforms. You will design and implement high-performance backend services using Java and Spring Boot, working on systems that process millions of transactions daily.',
        'requirements': '5+ years Java development experience. Strong knowledge of Spring Boot, Hibernate/JPA, and REST API design. Experience with microservices architecture and event-driven systems using Kafka. Financial services experience preferred. Bachelor\'s degree in Computer Science or related field.',
    },
    {
        'title': 'Java Backend Engineer',
        'company': 'Amazon',
        'location': 'Seattle, WA',
        'remote': True,
        'stream': 'backend',
        'experience_level': 'mid',
        'salary_min': 130000,
        'salary_max': 175000,
        'is_featured': True,
        'skills': 'Java, Spring Boot, Hibernate, AWS, Docker, Kubernetes, SQL, REST API',
        'description': 'Build scalable backend services for Amazon\'s e-commerce platform. Work with cross-functional teams to deliver features that impact millions of customers worldwide.',
        'requirements': '3+ years of professional software development. Proficiency in Java, Spring Boot, and Hibernate. Experience with AWS services (EC2, S3, Lambda, ECS). Knowledge of Docker and Kubernetes. Strong SQL and database design skills.',
    },
    {
        'title': 'Full Stack Java Developer',
        'company': 'JPMorgan Chase',
        'location': 'Jersey City, NJ',
        'remote': False,
        'stream': 'fullstack',
        'experience_level': 'senior',
        'salary_min': 140000,
        'salary_max': 185000,
        'is_featured': True,
        'skills': 'Java, Spring Boot, Hibernate, React, TypeScript, REST API, SQL, Agile',
        'description': 'Develop full-stack solutions for banking applications. Lead technical design discussions and mentor junior developers while delivering secure, scalable financial applications.',
        'requirements': '5+ years full stack development. Expert in Java/Spring Boot backend and React frontend. Hibernate/JPA experience required. Understanding of OAuth2, JWT security. Agile/Scrum experience.',
    },
    {
        'title': 'Microservices Architect',
        'company': 'Netflix',
        'location': 'Los Gatos, CA',
        'remote': True,
        'stream': 'microservices',
        'experience_level': 'lead',
        'salary_min': 200000,
        'salary_max': 280000,
        'is_featured': True,
        'skills': 'Java, Spring Boot, Spring Cloud, Microservices, Kafka, Docker, Kubernetes, AWS, System Design',
        'description': 'Architect and lead the design of microservices powering Netflix\'s streaming platform. Define technical standards and drive adoption of cloud-native patterns across engineering teams.',
        'requirements': '8+ years software engineering, 3+ years architecture experience. Deep expertise in microservices, Spring Cloud, and distributed systems. Experience with Kafka, Docker, Kubernetes on AWS. Strong system design and communication skills.',
    },
    {
        'title': 'Junior Java Developer',
        'company': 'Accenture',
        'location': 'Chicago, IL',
        'remote': True,
        'stream': 'enterprise',
        'experience_level': 'junior',
        'salary_min': 70000,
        'salary_max': 95000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, Hibernate, SQL, REST API, Git, Agile, JUnit',
        'description': 'Start your career building enterprise Java applications for Fortune 500 clients. Receive mentorship from senior engineers while working on diverse technology projects.',
        'requirements': '0-2 years experience or new graduate. Knowledge of Java, Spring Boot basics, and SQL. Familiarity with Hibernate/JPA. Understanding of REST API concepts. Strong problem-solving skills.',
    },
    {
        'title': 'Spring Boot Hibernate Developer',
        'company': 'Infosys',
        'location': 'Bangalore, India',
        'remote': True,
        'stream': 'backend',
        'experience_level': 'mid',
        'salary_min': 25000,
        'salary_max': 45000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, Hibernate, JPA, MySQL, REST API, Maven, JUnit, Mockito',
        'description': 'Develop and maintain enterprise applications using Java Spring Boot and Hibernate ORM. Work with international clients on digital transformation projects.',
        'requirements': '3-5 years Java development. Strong Spring Boot and Hibernate/JPA skills. MySQL or PostgreSQL experience. REST API development. Unit testing with JUnit and Mockito.',
    },
    {
        'title': 'Cloud Native Java Engineer',
        'company': 'Google',
        'location': 'Mountain View, CA',
        'remote': False,
        'stream': 'cloud',
        'experience_level': 'senior',
        'salary_min': 170000,
        'salary_max': 230000,
        'is_featured': True,
        'skills': 'Java, Spring Boot, GCP, Kubernetes, Docker, Microservices, gRPC, SQL',
        'description': 'Build cloud-native services on Google Cloud Platform. Design resilient, scalable systems using modern Java frameworks and container orchestration.',
        'requirements': '5+ years Java/Spring Boot development. GCP experience (GKE, Cloud Run, Pub/Sub). Kubernetes and Docker proficiency. Microservices and gRPC experience. Strong distributed systems knowledge.',
    },
    {
        'title': 'DevOps Java Engineer',
        'company': 'Microsoft',
        'location': 'Redmond, WA',
        'remote': True,
        'stream': 'devops',
        'experience_level': 'senior',
        'salary_min': 145000,
        'salary_max': 195000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, Azure, Docker, Kubernetes, CI/CD, Jenkins, Terraform',
        'description': 'Bridge development and operations by building robust CI/CD pipelines and infrastructure for Java microservices on Azure cloud platform.',
        'requirements': '5+ years combined DevOps and Java development. Azure DevOps, AKS experience. CI/CD pipeline design (Jenkins, GitHub Actions). Infrastructure as Code (Terraform). Spring Boot application deployment experience.',
    },
    {
        'title': 'Data Engineer - Java',
        'company': 'Uber',
        'location': 'San Francisco, CA',
        'remote': True,
        'stream': 'data',
        'experience_level': 'mid',
        'salary_min': 135000,
        'salary_max': 180000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, Kafka, SQL, PostgreSQL, Redis, AWS, Hibernate',
        'description': 'Build real-time data pipelines processing ride and delivery data. Develop streaming applications using Kafka and Spring Boot for analytics and machine learning teams.',
        'requirements': '3-5 years data engineering or backend development. Java and Spring Boot proficiency. Kafka/streaming experience. Strong SQL skills with PostgreSQL. AWS data services knowledge.',
    },
    {
        'title': 'Mobile Backend Engineer',
        'company': 'Spotify',
        'location': 'Stockholm, Sweden',
        'remote': True,
        'stream': 'mobile',
        'experience_level': 'senior',
        'salary_min': 90000,
        'salary_max': 130000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, REST API, Redis, PostgreSQL, Kafka, Docker, Security',
        'description': 'Power Spotify\'s mobile apps with high-performance backend APIs. Build services handling billions of requests for music streaming, playlists, and social features.',
        'requirements': '5+ years backend development. Java/Spring Boot expertise. High-traffic API design experience. Redis caching, PostgreSQL optimization. OAuth2/JWT security implementation.',
    },
    {
        'title': 'Enterprise Java Architect',
        'company': 'IBM',
        'location': 'Austin, TX',
        'remote': True,
        'stream': 'enterprise',
        'experience_level': 'lead',
        'salary_min': 160000,
        'salary_max': 220000,
        'is_featured': True,
        'skills': 'Java, Spring Boot, Hibernate, Microservices, System Design, Design Patterns, SQL, Agile',
        'description': 'Lead architecture for enterprise Java solutions serving global clients. Drive modernization of legacy systems to cloud-native Spring Boot microservices.',
        'requirements': '10+ years Java enterprise development. Architecture and design patterns expertise. Spring Boot/Hibernate mastery. Legacy modernization experience. Client-facing communication skills.',
    },
    {
        'title': 'Java Spring Intern',
        'company': 'SAP',
        'location': 'Walldorf, Germany',
        'remote': False,
        'stream': 'backend',
        'experience_level': 'intern',
        'salary_min': 35000,
        'salary_max': 45000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, Hibernate, SQL, Git, REST API, JUnit',
        'description': 'Summer internship program for aspiring Java developers. Work on real SAP products using Spring Boot and Hibernate while learning enterprise software development practices.',
        'requirements': 'Currently pursuing CS or related degree. Java programming coursework. Basic understanding of Spring framework. Eagerness to learn Hibernate and REST APIs. Good communication skills.',
    },
    {
        'title': 'Backend Engineer - Payments',
        'company': 'Stripe',
        'location': 'San Francisco, CA',
        'remote': True,
        'stream': 'fintech',
        'experience_level': 'senior',
        'salary_min': 175000,
        'salary_max': 240000,
        'is_featured': True,
        'skills': 'Java, Spring Boot, Hibernate, Kafka, PostgreSQL, Redis, Security, Microservices',
        'description': 'Build the infrastructure powering online payments for millions of businesses. Design fault-tolerant, secure payment processing systems with Java and Spring Boot.',
        'requirements': '5+ years backend engineering. Java/Spring Boot at scale. Payment systems or fintech experience. Kafka event processing. PostgreSQL and Redis expertise. Security best practices (PCI compliance).',
    },
    {
        'title': 'Senior Hibernate Developer',
        'company': 'TCS',
        'location': 'Hyderabad, India',
        'remote': True,
        'stream': 'backend',
        'experience_level': 'senior',
        'salary_min': 30000,
        'salary_max': 55000,
        'is_featured': False,
        'skills': 'Java, Hibernate, JPA, Spring Boot, Oracle, SQL, REST API, Maven',
        'description': 'Specialize in data persistence layer development using Hibernate and JPA. Optimize ORM mappings and queries for high-performance enterprise applications.',
        'requirements': '5+ years Java with 3+ years Hibernate/JPA focus. Oracle or PostgreSQL expertise. Query optimization and N+1 problem resolution. Spring Boot integration experience.',
    },
    {
        'title': 'Full Stack Engineer - Java/React',
        'company': 'Meta',
        'location': 'Menlo Park, CA',
        'remote': False,
        'stream': 'fullstack',
        'experience_level': 'mid',
        'salary_min': 150000,
        'salary_max': 200000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, React, TypeScript, GraphQL, Hibernate, SQL, Docker',
        'description': 'Build internal tools and platforms connecting Meta\'s engineering teams. Develop full-stack features with Java Spring Boot backend and React frontend.',
        'requirements': '3-5 years full stack development. Java/Spring Boot and React/TypeScript. GraphQL API experience. Hibernate for data layer. Docker containerization.',
    },
    {
        'title': 'Platform Engineer - Java',
        'company': 'LinkedIn',
        'location': 'Sunnyvale, CA',
        'remote': True,
        'stream': 'cloud',
        'experience_level': 'senior',
        'salary_min': 155000,
        'salary_max': 210000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, Kafka, Kubernetes, Docker, Azure, Microservices, SQL',
        'description': 'Build platform services that power LinkedIn\'s professional network. Create shared infrastructure and frameworks used by hundreds of engineering teams.',
        'requirements': '5+ years platform or backend engineering. Java/Spring Boot expertise. Kafka and event-driven architecture. Kubernetes on Azure. API framework design experience.',
    },
    {
        'title': 'Java API Developer',
        'company': 'Salesforce',
        'location': 'San Francisco, CA',
        'remote': True,
        'stream': 'backend',
        'experience_level': 'mid',
        'salary_min': 125000,
        'salary_max': 165000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, REST API, Hibernate, PostgreSQL, OAuth2, JUnit, Agile',
        'description': 'Design and implement RESTful APIs for Salesforce platform integrations. Build secure, well-documented APIs following industry best practices.',
        'requirements': '3-5 years API development. Java/Spring Boot REST API design. Hibernate/JPA with PostgreSQL. OAuth2 authentication. API documentation (OpenAPI/Swagger). Test-driven development.',
    },
    {
        'title': 'Lead Java Engineer',
        'company': 'Capital One',
        'location': 'McLean, VA',
        'remote': True,
        'stream': 'fintech',
        'experience_level': 'lead',
        'salary_min': 170000,
        'salary_max': 230000,
        'is_featured': True,
        'skills': 'Java, Spring Boot, Hibernate, AWS, Microservices, Kafka, Kubernetes, System Design',
        'description': 'Lead a team of engineers building cloud-native banking services. Drive technical strategy for Java microservices platform on AWS.',
        'requirements': '8+ years Java development, 2+ years team lead. Spring Boot/Hibernate expert. AWS cloud architecture. Microservices with Kafka. People management and mentoring skills.',
    },
    {
        'title': 'Software Engineer II - Java',
        'company': 'Walmart',
        'location': 'Bentonville, AR',
        'remote': True,
        'stream': 'backend',
        'experience_level': 'mid',
        'salary_min': 110000,
        'salary_max': 145000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, Hibernate, SQL, Redis, Kafka, Docker, REST API',
        'description': 'Build backend services for Walmart\'s e-commerce and supply chain platforms. Handle high-traffic systems serving millions of customers daily.',
        'requirements': '3-5 years Java backend development. Spring Boot and Hibernate proficiency. SQL database optimization. Redis caching patterns. Event-driven architecture with Kafka.',
    },
    {
        'title': 'Spring Cloud Microservices Developer',
        'company': 'Cognizant',
        'location': 'Chennai, India',
        'remote': True,
        'stream': 'microservices',
        'experience_level': 'mid',
        'salary_min': 20000,
        'salary_max': 40000,
        'is_featured': False,
        'skills': 'Java, Spring Boot, Spring Cloud, Hibernate, Docker, Kubernetes, REST API, SQL',
        'description': 'Develop microservices solutions for global clients using Spring Cloud ecosystem. Implement service discovery, circuit breakers, and API gateways.',
        'requirements': '3-5 years Java development. Spring Boot and Spring Cloud (Eureka, Gateway, Config). Hibernate/JPA. Docker and Kubernetes deployment. Microservices design patterns.',
    },
]


class Command(BaseCommand):
    help = 'Seed the database with sample Java/Spring Boot job listings'

    def handle(self, *args, **options):
        if Job.objects.exists():
            self.stdout.write('Jobs already exist. Skipping seed.')
            return

        for data in JOBS_DATA:
            Job.objects.create(**data)

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {len(JOBS_DATA)} jobs'))
